Added link to online workshop blog post prompts
carpentries/docs.carpentries.org pull request #644
Opened 2020-07-07 07:01 UTC by elletjies

Just need to check that my link to the page is correct!

2020-07-09 07:35 UTC, elletjies commented
@serahrono  and @kmomar I inserted the prompts here :)

2020-08-19 06:36 UTC, serahrono approved these changes

2020-08-19 06:59 UTC, serahrono requested changes
please move  lines 15 - 21 (themed discussions) to the webinars and community calls section.

2020-08-19 06:59 UTC, serahrono commented
Hi @elletjies, I would suggest moving everything listed between lines 15 - 21 (themed discussions) to the webinars and community calls section. That way, we can point people to one section to all videos on online workshops

2020-08-19 07:34 UTC, merged