expand guidelines for blog post submissions
carpentries/docs.carpentries.org pull request #710
Opened 2021-02-08 11:34 UTC by fmichonneau

draft of expanded recommendations for file naming when contributing to our website

2021-02-08 11:34 UTC, fmichonneau commented on topic_folders/communications/guides/submit_blog_post.md
> +* For titles, we recommend ...
@kmomar please complete

2021-02-10 17:54 UTC, fmichonneau commented on topic_folders/communications/guides/submit_blog_post.md
> +* For titles, we recommend making sure the title is descriptive and uses no more than 5-7 words. EX: How We Use Feedback at The Carpentries
should we mention using title case here?

2021-02-10 18:00 UTC, fmichonneau commented on topic_folders/communications/guides/submit_blog_post.md
> +* For headings, we recommend a full sentence that succinctly describes the contents of the blog. EX: Read on to learn about our strategic plan progress through Q3 2020 (July - September)
Could we maybe add a few more recommendations here like "Start with an actionable verb for posts that involve the community, e.g., 'Become a mentor or mentee for the first cycle of 2021 Mentoring Groups!'", or "Avoid starting the heading with 'in this blog post we...'", anything else?

2021-03-01 15:29 UTC, fmichonneau commented
@kmomar @serahrono is this ready to be merged?

2021-03-01 15:48 UTC, kmomar commented
@fmichonneau in my opinion yes, but I will leave it for @serahrono to confirm.

2021-03-04 09:29 UTC, serahrono requested changes
thank you for working on this @fmichonneau and @kmomar. Questions for you, 
- are there short guides / tutorials from our resource bank or elsewhere that we can point to that walk people through how to write good blog post headlines? I like that this is a clear set of dos and don'ts, and would like us to qualify some of the best practice recommendations / or at least help make it easier for people to do the right thing
- because we are recommending title case use for our blog post titles, I would like us to go a step further and state what convention we recommend using [from this list](https://titlecaseconverter.com/rules/). Once we know, we would be in a good position to point people to the [titlecaseconverter tool](https://titlecaseconverter.com) as a good way to make it easier to get it right, and correct any inconsistencies during the review process.

2021-03-22 19:01 UTC, kmomar commented
Hi @serahrono: regarding your points above,
- From my cursory search, most of the blog post headline guidelines I could find were for increasing clicks and traffic, which is not necessarily what I think we are looking for. I am happy to search more, but wanted to report back on that.
- I think that we should use AP style, if only for the reason that I am most familiar with it and as one of the team members who works on the blog it would help my work, but if there are salient criticisms then I am happy to change that.

2021-09-20 14:32 UTC, maneesha commented
This had been pending review from Serah a few months ago.  @kmomar  @acrall  given the notes above, is this ok to merge?

2021-09-22 20:07 UTC, acrall commented
@maneesha, @kmomar and I discussed, and decided to merge

2021-09-22 20:08 UTC, merged