change Calendly link to sher's
carpentries/docs.carpentries.org pull request #950
Opened 2023-12-29 19:56 UTC by karenword

We discussed this, but be sure to check with @sheraaronhurt before merging

2024-01-04 19:18 UTC, maneesha commented
@sheraaronhurt 
Note that the link in this PR (https://calendly.com/sheraaron/instructor-training-makeup) goes to a 45 minute session on your calendar but the text says it is 50 minutes.  When you review this PR can you fix either this text or the calendly event?

2024-01-08 17:52 UTC, sheraaronhurt requested changes
@maneesha I made the adjustment to the time

2024-01-08 17:58 UTC, maneesha approved these changes

2024-01-08 18:42 UTC, maneesha approved these changes

2024-01-08 18:42 UTC, merged